### ISSUE TITLE
Are all the teams supposed to edit the very same presentation?

### ISSUE THREAD

**Issue by hamddan4** [mcv-m6-video/mcv-m6-2020-team5#2]
Just to make sure, we want to know if all the teams have to edit the very same presentation provided by [this link](https://docs.google.com/presentation/d/1AVxaY5epmUaZSwrJ3hu4xbOBTjpmJxgu0Pms7UMf96Q/edit#slide=id.g7e4704d192_0_6). We like this idea but as we have never seen this methodology, we just wanted to make it clear.

**Comment by jrhupc** [comment]
Hello,

Correct. Please add your slides to the same presentation!

Regards,

**Comment by hamddan4** [comment]
And the slides that are titled as "Team X, max 3 slides", do every team have to upload their slides, right? I mean, at the end, there will be (with a maximum of 3 slides) N times the same task, one for every team?

**Comment by xavigiro** [comment]
Yes, this is correct. 3 slides per task/subtask. Unless that task is actually filling values in a table to allow comparison.
